### ISSUE TITLE
Crashing On Search

### ISSUE THREAD

**Issue by lkjfdsaofmc** [AlexModGuy/CloudStorage#33]
Whenever anyone on my server tries to search anything whatsoever in the cloud storage UI (using the built in search function) my server instantaneously crashes.  The crash occurs after any character is entered in the search field by any player.  I've attached a server crash log.
[crash-2022-08-29_20.32.51-server.txt](https://github.com/AlexModGuy/CloudStorage/files/9449430/crash-2022-08-29_20.32.51-server.txt)

**Comment by ShadowzOfTheDark** [comment]
Remove any of the silent gear items in your cloud storage as those are causing the crash. I am having a very similar issue with tetra. Seems like certain edge cases where mods don't supply tooltips/text where cloud storage expects it yields an error.
[crash-2022-09-14_21.52.33-server.txt](https://github.com/AlexModGuy/CloudStorage/files/9571118/crash-2022-09-14_21.52.33-server.txt)

**Comment by Frefreak** [comment]
[crash-2023-07-15_10.44.29-server.txt](https://github.com/AlexModGuy/CloudStorage/files/12060157/crash-2023-07-15_10.44.29-server.txt)
I encountered this too. From the call stack in my case it seems cloud storage are trying to search the tooltip, and powah's tooltip related logic reference client side class which causes the crash. In normal case tooltip rendering only happens in client side and will not cause any issue, but in here this is happening in the server side.

**Comment by GotoFinal** [comment]
No attention to this issue? its clearly issue with cloud storage trying to use client side functions making it unusable on most modpacks... for now in own fork just disabled searching by this


EDIT: ok i see its fixed apparently here https://github.com/AlexModGuy/CloudStorage/commit/08395263ef4326eb3691edaf37e496b6dd002613 but wrongly because its catching only exceptions and not errors (and the whole idea is just horrible, very laggy too on server, single big inventory can drop tps to 0) so i need to backport it myseelf for dawncraft im playin

**Comment by SettingDust** [comment]
> No attention to this issue? its clearly issue with cloud storage trying to use client side functions making it unusable on most modpacks... for now in own fork just disabled searching by this
> 
> EDIT: ok i see its fixed apparently here [0839526](https://github.com/AlexModGuy/CloudStorage/commit/08395263ef4326eb3691edaf37e496b6dd002613) but wrongly because its catching only exceptions and not errors (and the whole idea is just horrible, very laggy too on server, single big inventory can drop tps to 0) so i need to backport it myseelf for dawncraft im playin

The same fix is applied in DawnCraft by me. I'll fix this issue in DawnCraft next version
https://github.com/SettingDust/dawncraft-fixes/blob/main/src/main/java/io/github/settingdust/dawncraftfixes/mixin/cloudstorage/MixinCloudChestMenu.java#L29-L40

EDIT: fixed in 0.12.1 https://legacy.curseforge.com/minecraft/mc-mods/mod-compat-fixes/files/4738685
